/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TakeoffRouteImport } from './routes/takeoff'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SubcontractorsRouteImport } from './routes/subcontractors'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PriceListsRouteImport } from './routes/price-lists'
import { Route as PortalAccessRouteImport } from './routes/portal-access'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EstimatesRouteImport } from './routes/estimates'
import { Route as DownloadFreeEstimatingTemplateRouteImport } from './routes/download-free-estimating-template'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as ChangeOrdersRouteImport } from './routes/change-orders'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiEstimateRouteImport } from './routes/ai-estimate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as FreeEstimatingTemplatePdfIndexRouteImport } from './routes/free-estimating-template-pdf/index'
import { Route as EstimatesIndexRouteImport } from './routes/estimates.index'
import { Route as ViewTokenRouteImport } from './routes/view.$token'
import { Route as TradeSlugRouteImport } from './routes/trade.$slug'
import { Route as SubscribeSuccessRouteImport } from './routes/subscribe.success'
import { Route as SubscribeCancelRouteImport } from './routes/subscribe.cancel'
import { Route as SubscribePlanRouteImport } from './routes/subscribe.$plan'
import { Route as SignEstimateIdRouteImport } from './routes/sign.$estimateId'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as EstimatesNewRouteImport } from './routes/estimates.new'
import { Route as EstimatesIdRouteImport } from './routes/estimates.$id'
import { Route as ContractsIdRouteImport } from './routes/contracts.$id'
import { Route as CoIdRouteImport } from './routes/co.$id'
import { Route as ChangeOrdersIdRouteImport } from './routes/change-orders.$id'
import { Route as TemplatesMarketplaceIndexRouteImport } from './routes/templates/marketplace/index'
import { Route as TemplatesMarketplaceListingIdRouteImport } from './routes/templates/marketplace/$listingId'
import { Route as PortalEstimateIdRouteImport } from './routes/portal/estimate.$id'
import { Route as PortalChangeOrderIdRouteImport } from './routes/portal/change-order.$id'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TakeoffRoute = TakeoffRouteImport.update({
  id: '/takeoff',
  path: '/takeoff',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SubcontractorsRoute = SubcontractorsRouteImport.update({
  id: '/subcontractors',
  path: '/subcontractors',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceListsRoute = PriceListsRouteImport.update({
  id: '/price-lists',
  path: '/price-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAccessRoute = PortalAccessRouteImport.update({
  id: '/portal-access',
  path: '/portal-access',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatesRoute = EstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadFreeEstimatingTemplateRoute =
  DownloadFreeEstimatingTemplateRouteImport.update({
    id: '/download-free-estimating-template',
    path: '/download-free-estimating-template',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeOrdersRoute = ChangeOrdersRouteImport.update({
  id: '/change-orders',
  path: '/change-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEstimateRoute = AiEstimateRouteImport.update({
  id: '/ai-estimate',
  path: '/ai-estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeEstimatingTemplatePdfIndexRoute =
  FreeEstimatingTemplatePdfIndexRouteImport.update({
    id: '/free-estimating-template-pdf/',
    path: '/free-estimating-template-pdf/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EstimatesIndexRoute = EstimatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EstimatesRoute,
} as any)
const ViewTokenRoute = ViewTokenRouteImport.update({
  id: '/view/$token',
  path: '/view/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeSlugRoute = TradeSlugRouteImport.update({
  id: '/trade/$slug',
  path: '/trade/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeSuccessRoute = SubscribeSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => SubscribeRoute,
} as any)
const SubscribeCancelRoute = SubscribeCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => SubscribeRoute,
} as any)
const SubscribePlanRoute = SubscribePlanRouteImport.update({
  id: '/$plan',
  path: '/$plan',
  getParentRoute: () => SubscribeRoute,
} as any)
const SignEstimateIdRoute = SignEstimateIdRouteImport.update({
  id: '/sign/$estimateId',
  path: '/sign/$estimateId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvoicesRoute,
} as any)
const EstimatesNewRoute = EstimatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EstimatesRoute,
} as any)
const EstimatesIdRoute = EstimatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EstimatesRoute,
} as any)
const ContractsIdRoute = ContractsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContractsRoute,
} as any)
const CoIdRoute = CoIdRouteImport.update({
  id: '/co/$id',
  path: '/co/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeOrdersIdRoute = ChangeOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChangeOrdersRoute,
} as any)
const TemplatesMarketplaceIndexRoute =
  TemplatesMarketplaceIndexRouteImport.update({
    id: '/marketplace/',
    path: '/marketplace/',
    getParentRoute: () => TemplatesRoute,
  } as any)
const TemplatesMarketplaceListingIdRoute =
  TemplatesMarketplaceListingIdRouteImport.update({
    id: '/marketplace/$listingId',
    path: '/marketplace/$listingId',
    getParentRoute: () => TemplatesRoute,
  } as any)
const PortalEstimateIdRoute = PortalEstimateIdRouteImport.update({
  id: '/portal/estimate/$id',
  path: '/portal/estimate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalChangeOrderIdRoute = PortalChangeOrderIdRouteImport.update({
  id: '/portal/change-order/$id',
  path: '/portal/change-order/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-estimate': typeof AiEstimateRoute
  '/analytics': typeof AnalyticsRoute
  '/automation': typeof AutomationRoute
  '/blog': typeof BlogRoute
  '/change-orders': typeof ChangeOrdersRouteWithChildren
  '/contracts': typeof ContractsRouteWithChildren
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/download-free-estimating-template': typeof DownloadFreeEstimatingTemplateRoute
  '/estimates': typeof EstimatesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/materials': typeof MaterialsRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pipeline': typeof PipelineRoute
  '/portal-access': typeof PortalAccessRoute
  '/price-lists': typeof PriceListsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/signup': typeof SignupRoute
  '/subcontractors': typeof SubcontractorsRoute
  '/subscribe': typeof SubscribeRouteWithChildren
  '/takeoff': typeof TakeoffRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/change-orders/$id': typeof ChangeOrdersIdRoute
  '/co/$id': typeof CoIdRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/estimates/$id': typeof EstimatesIdRoute
  '/estimates/new': typeof EstimatesNewRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/portal/login': typeof PortalLoginRoute
  '/sign/$estimateId': typeof SignEstimateIdRoute
  '/subscribe/$plan': typeof SubscribePlanRoute
  '/subscribe/cancel': typeof SubscribeCancelRoute
  '/subscribe/success': typeof SubscribeSuccessRoute
  '/trade/$slug': typeof TradeSlugRoute
  '/view/$token': typeof ViewTokenRoute
  '/estimates/': typeof EstimatesIndexRoute
  '/free-estimating-template-pdf/': typeof FreeEstimatingTemplatePdfIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/change-order/$id': typeof PortalChangeOrderIdRoute
  '/portal/estimate/$id': typeof PortalEstimateIdRoute
  '/templates/marketplace/$listingId': typeof TemplatesMarketplaceListingIdRoute
  '/templates/marketplace/': typeof TemplatesMarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-estimate': typeof AiEstimateRoute
  '/analytics': typeof AnalyticsRoute
  '/automation': typeof AutomationRoute
  '/blog': typeof BlogRoute
  '/change-orders': typeof ChangeOrdersRouteWithChildren
  '/contracts': typeof ContractsRouteWithChildren
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/download-free-estimating-template': typeof DownloadFreeEstimatingTemplateRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/materials': typeof MaterialsRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pipeline': typeof PipelineRoute
  '/portal-access': typeof PortalAccessRoute
  '/price-lists': typeof PriceListsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/signup': typeof SignupRoute
  '/subcontractors': typeof SubcontractorsRoute
  '/subscribe': typeof SubscribeRouteWithChildren
  '/takeoff': typeof TakeoffRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/change-orders/$id': typeof ChangeOrdersIdRoute
  '/co/$id': typeof CoIdRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/estimates/$id': typeof EstimatesIdRoute
  '/estimates/new': typeof EstimatesNewRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/portal/login': typeof PortalLoginRoute
  '/sign/$estimateId': typeof SignEstimateIdRoute
  '/subscribe/$plan': typeof SubscribePlanRoute
  '/subscribe/cancel': typeof SubscribeCancelRoute
  '/subscribe/success': typeof SubscribeSuccessRoute
  '/trade/$slug': typeof TradeSlugRoute
  '/view/$token': typeof ViewTokenRoute
  '/estimates': typeof EstimatesIndexRoute
  '/free-estimating-template-pdf': typeof FreeEstimatingTemplatePdfIndexRoute
  '/portal': typeof PortalIndexRoute
  '/portal/change-order/$id': typeof PortalChangeOrderIdRoute
  '/portal/estimate/$id': typeof PortalEstimateIdRoute
  '/templates/marketplace/$listingId': typeof TemplatesMarketplaceListingIdRoute
  '/templates/marketplace': typeof TemplatesMarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-estimate': typeof AiEstimateRoute
  '/analytics': typeof AnalyticsRoute
  '/automation': typeof AutomationRoute
  '/blog': typeof BlogRoute
  '/change-orders': typeof ChangeOrdersRouteWithChildren
  '/contracts': typeof ContractsRouteWithChildren
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/download-free-estimating-template': typeof DownloadFreeEstimatingTemplateRoute
  '/estimates': typeof EstimatesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/materials': typeof MaterialsRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pipeline': typeof PipelineRoute
  '/portal-access': typeof PortalAccessRoute
  '/price-lists': typeof PriceListsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/signup': typeof SignupRoute
  '/subcontractors': typeof SubcontractorsRoute
  '/subscribe': typeof SubscribeRouteWithChildren
  '/takeoff': typeof TakeoffRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/change-orders/$id': typeof ChangeOrdersIdRoute
  '/co/$id': typeof CoIdRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/estimates/$id': typeof EstimatesIdRoute
  '/estimates/new': typeof EstimatesNewRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/portal/login': typeof PortalLoginRoute
  '/sign/$estimateId': typeof SignEstimateIdRoute
  '/subscribe/$plan': typeof SubscribePlanRoute
  '/subscribe/cancel': typeof SubscribeCancelRoute
  '/subscribe/success': typeof SubscribeSuccessRoute
  '/trade/$slug': typeof TradeSlugRoute
  '/view/$token': typeof ViewTokenRoute
  '/estimates/': typeof EstimatesIndexRoute
  '/free-estimating-template-pdf/': typeof FreeEstimatingTemplatePdfIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/change-order/$id': typeof PortalChangeOrderIdRoute
  '/portal/estimate/$id': typeof PortalEstimateIdRoute
  '/templates/marketplace/$listingId': typeof TemplatesMarketplaceListingIdRoute
  '/templates/marketplace/': typeof TemplatesMarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-estimate'
    | '/analytics'
    | '/automation'
    | '/blog'
    | '/change-orders'
    | '/contracts'
    | '/customers'
    | '/dashboard'
    | '/download-free-estimating-template'
    | '/estimates'
    | '/forgot-password'
    | '/import'
    | '/integrations'
    | '/invoices'
    | '/login'
    | '/logout'
    | '/materials'
    | '/onboarding'
    | '/payment-success'
    | '/pipeline'
    | '/portal-access'
    | '/price-lists'
    | '/reports'
    | '/reset-password'
    | '/schedule'
    | '/settings'
    | '/share'
    | '/signup'
    | '/subcontractors'
    | '/subscribe'
    | '/takeoff'
    | '/team'
    | '/templates'
    | '/change-orders/$id'
    | '/co/$id'
    | '/contracts/$id'
    | '/estimates/$id'
    | '/estimates/new'
    | '/invoices/$id'
    | '/portal/login'
    | '/sign/$estimateId'
    | '/subscribe/$plan'
    | '/subscribe/cancel'
    | '/subscribe/success'
    | '/trade/$slug'
    | '/view/$token'
    | '/estimates/'
    | '/free-estimating-template-pdf/'
    | '/portal/'
    | '/portal/change-order/$id'
    | '/portal/estimate/$id'
    | '/templates/marketplace/$listingId'
    | '/templates/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-estimate'
    | '/analytics'
    | '/automation'
    | '/blog'
    | '/change-orders'
    | '/contracts'
    | '/customers'
    | '/dashboard'
    | '/download-free-estimating-template'
    | '/forgot-password'
    | '/import'
    | '/integrations'
    | '/invoices'
    | '/login'
    | '/logout'
    | '/materials'
    | '/onboarding'
    | '/payment-success'
    | '/pipeline'
    | '/portal-access'
    | '/price-lists'
    | '/reports'
    | '/reset-password'
    | '/schedule'
    | '/settings'
    | '/share'
    | '/signup'
    | '/subcontractors'
    | '/subscribe'
    | '/takeoff'
    | '/team'
    | '/templates'
    | '/change-orders/$id'
    | '/co/$id'
    | '/contracts/$id'
    | '/estimates/$id'
    | '/estimates/new'
    | '/invoices/$id'
    | '/portal/login'
    | '/sign/$estimateId'
    | '/subscribe/$plan'
    | '/subscribe/cancel'
    | '/subscribe/success'
    | '/trade/$slug'
    | '/view/$token'
    | '/estimates'
    | '/free-estimating-template-pdf'
    | '/portal'
    | '/portal/change-order/$id'
    | '/portal/estimate/$id'
    | '/templates/marketplace/$listingId'
    | '/templates/marketplace'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-estimate'
    | '/analytics'
    | '/automation'
    | '/blog'
    | '/change-orders'
    | '/contracts'
    | '/customers'
    | '/dashboard'
    | '/download-free-estimating-template'
    | '/estimates'
    | '/forgot-password'
    | '/import'
    | '/integrations'
    | '/invoices'
    | '/login'
    | '/logout'
    | '/materials'
    | '/onboarding'
    | '/payment-success'
    | '/pipeline'
    | '/portal-access'
    | '/price-lists'
    | '/reports'
    | '/reset-password'
    | '/schedule'
    | '/settings'
    | '/share'
    | '/signup'
    | '/subcontractors'
    | '/subscribe'
    | '/takeoff'
    | '/team'
    | '/templates'
    | '/change-orders/$id'
    | '/co/$id'
    | '/contracts/$id'
    | '/estimates/$id'
    | '/estimates/new'
    | '/invoices/$id'
    | '/portal/login'
    | '/sign/$estimateId'
    | '/subscribe/$plan'
    | '/subscribe/cancel'
    | '/subscribe/success'
    | '/trade/$slug'
    | '/view/$token'
    | '/estimates/'
    | '/free-estimating-template-pdf/'
    | '/portal/'
    | '/portal/change-order/$id'
    | '/portal/estimate/$id'
    | '/templates/marketplace/$listingId'
    | '/templates/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiEstimateRoute: typeof AiEstimateRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AutomationRoute: typeof AutomationRoute
  BlogRoute: typeof BlogRoute
  ChangeOrdersRoute: typeof ChangeOrdersRouteWithChildren
  ContractsRoute: typeof ContractsRouteWithChildren
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DownloadFreeEstimatingTemplateRoute: typeof DownloadFreeEstimatingTemplateRoute
  EstimatesRoute: typeof EstimatesRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImportRoute: typeof ImportRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InvoicesRoute: typeof InvoicesRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  MaterialsRoute: typeof MaterialsRoute
  OnboardingRoute: typeof OnboardingRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PipelineRoute: typeof PipelineRoute
  PortalAccessRoute: typeof PortalAccessRoute
  PriceListsRoute: typeof PriceListsRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  ShareRoute: typeof ShareRoute
  SignupRoute: typeof SignupRoute
  SubcontractorsRoute: typeof SubcontractorsRoute
  SubscribeRoute: typeof SubscribeRouteWithChildren
  TakeoffRoute: typeof TakeoffRoute
  TeamRoute: typeof TeamRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  CoIdRoute: typeof CoIdRoute
  PortalLoginRoute: typeof PortalLoginRoute
  SignEstimateIdRoute: typeof SignEstimateIdRoute
  TradeSlugRoute: typeof TradeSlugRoute
  ViewTokenRoute: typeof ViewTokenRoute
  FreeEstimatingTemplatePdfIndexRoute: typeof FreeEstimatingTemplatePdfIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalChangeOrderIdRoute: typeof PortalChangeOrderIdRoute
  PortalEstimateIdRoute: typeof PortalEstimateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takeoff': {
      id: '/takeoff'
      path: '/takeoff'
      fullPath: '/takeoff'
      preLoaderRoute: typeof TakeoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subcontractors': {
      id: '/subcontractors'
      path: '/subcontractors'
      fullPath: '/subcontractors'
      preLoaderRoute: typeof SubcontractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-lists': {
      id: '/price-lists'
      path: '/price-lists'
      fullPath: '/price-lists'
      preLoaderRoute: typeof PriceListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-access': {
      id: '/portal-access'
      path: '/portal-access'
      fullPath: '/portal-access'
      preLoaderRoute: typeof PortalAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimates': {
      id: '/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof EstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download-free-estimating-template': {
      id: '/download-free-estimating-template'
      path: '/download-free-estimating-template'
      fullPath: '/download-free-estimating-template'
      preLoaderRoute: typeof DownloadFreeEstimatingTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-orders': {
      id: '/change-orders'
      path: '/change-orders'
      fullPath: '/change-orders'
      preLoaderRoute: typeof ChangeOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-estimate': {
      id: '/ai-estimate'
      path: '/ai-estimate'
      fullPath: '/ai-estimate'
      preLoaderRoute: typeof AiEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-estimating-template-pdf/': {
      id: '/free-estimating-template-pdf/'
      path: '/free-estimating-template-pdf'
      fullPath: '/free-estimating-template-pdf/'
      preLoaderRoute: typeof FreeEstimatingTemplatePdfIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimates/': {
      id: '/estimates/'
      path: '/'
      fullPath: '/estimates/'
      preLoaderRoute: typeof EstimatesIndexRouteImport
      parentRoute: typeof EstimatesRoute
    }
    '/view/$token': {
      id: '/view/$token'
      path: '/view/$token'
      fullPath: '/view/$token'
      preLoaderRoute: typeof ViewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$slug': {
      id: '/trade/$slug'
      path: '/trade/$slug'
      fullPath: '/trade/$slug'
      preLoaderRoute: typeof TradeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/success': {
      id: '/subscribe/success'
      path: '/success'
      fullPath: '/subscribe/success'
      preLoaderRoute: typeof SubscribeSuccessRouteImport
      parentRoute: typeof SubscribeRoute
    }
    '/subscribe/cancel': {
      id: '/subscribe/cancel'
      path: '/cancel'
      fullPath: '/subscribe/cancel'
      preLoaderRoute: typeof SubscribeCancelRouteImport
      parentRoute: typeof SubscribeRoute
    }
    '/subscribe/$plan': {
      id: '/subscribe/$plan'
      path: '/$plan'
      fullPath: '/subscribe/$plan'
      preLoaderRoute: typeof SubscribePlanRouteImport
      parentRoute: typeof SubscribeRoute
    }
    '/sign/$estimateId': {
      id: '/sign/$estimateId'
      path: '/sign/$estimateId'
      fullPath: '/sign/$estimateId'
      preLoaderRoute: typeof SignEstimateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/estimates/new': {
      id: '/estimates/new'
      path: '/new'
      fullPath: '/estimates/new'
      preLoaderRoute: typeof EstimatesNewRouteImport
      parentRoute: typeof EstimatesRoute
    }
    '/estimates/$id': {
      id: '/estimates/$id'
      path: '/$id'
      fullPath: '/estimates/$id'
      preLoaderRoute: typeof EstimatesIdRouteImport
      parentRoute: typeof EstimatesRoute
    }
    '/contracts/$id': {
      id: '/contracts/$id'
      path: '/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof ContractsIdRouteImport
      parentRoute: typeof ContractsRoute
    }
    '/co/$id': {
      id: '/co/$id'
      path: '/co/$id'
      fullPath: '/co/$id'
      preLoaderRoute: typeof CoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-orders/$id': {
      id: '/change-orders/$id'
      path: '/$id'
      fullPath: '/change-orders/$id'
      preLoaderRoute: typeof ChangeOrdersIdRouteImport
      parentRoute: typeof ChangeOrdersRoute
    }
    '/templates/marketplace/': {
      id: '/templates/marketplace/'
      path: '/marketplace'
      fullPath: '/templates/marketplace/'
      preLoaderRoute: typeof TemplatesMarketplaceIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/marketplace/$listingId': {
      id: '/templates/marketplace/$listingId'
      path: '/marketplace/$listingId'
      fullPath: '/templates/marketplace/$listingId'
      preLoaderRoute: typeof TemplatesMarketplaceListingIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/portal/estimate/$id': {
      id: '/portal/estimate/$id'
      path: '/portal/estimate/$id'
      fullPath: '/portal/estimate/$id'
      preLoaderRoute: typeof PortalEstimateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/change-order/$id': {
      id: '/portal/change-order/$id'
      path: '/portal/change-order/$id'
      fullPath: '/portal/change-order/$id'
      preLoaderRoute: typeof PortalChangeOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChangeOrdersRouteChildren {
  ChangeOrdersIdRoute: typeof ChangeOrdersIdRoute
}

const ChangeOrdersRouteChildren: ChangeOrdersRouteChildren = {
  ChangeOrdersIdRoute: ChangeOrdersIdRoute,
}

const ChangeOrdersRouteWithChildren = ChangeOrdersRoute._addFileChildren(
  ChangeOrdersRouteChildren,
)

interface ContractsRouteChildren {
  ContractsIdRoute: typeof ContractsIdRoute
}

const ContractsRouteChildren: ContractsRouteChildren = {
  ContractsIdRoute: ContractsIdRoute,
}

const ContractsRouteWithChildren = ContractsRoute._addFileChildren(
  ContractsRouteChildren,
)

interface EstimatesRouteChildren {
  EstimatesIdRoute: typeof EstimatesIdRoute
  EstimatesNewRoute: typeof EstimatesNewRoute
  EstimatesIndexRoute: typeof EstimatesIndexRoute
}

const EstimatesRouteChildren: EstimatesRouteChildren = {
  EstimatesIdRoute: EstimatesIdRoute,
  EstimatesNewRoute: EstimatesNewRoute,
  EstimatesIndexRoute: EstimatesIndexRoute,
}

const EstimatesRouteWithChildren = EstimatesRoute._addFileChildren(
  EstimatesRouteChildren,
)

interface InvoicesRouteChildren {
  InvoicesIdRoute: typeof InvoicesIdRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesIdRoute: InvoicesIdRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface SubscribeRouteChildren {
  SubscribePlanRoute: typeof SubscribePlanRoute
  SubscribeCancelRoute: typeof SubscribeCancelRoute
  SubscribeSuccessRoute: typeof SubscribeSuccessRoute
}

const SubscribeRouteChildren: SubscribeRouteChildren = {
  SubscribePlanRoute: SubscribePlanRoute,
  SubscribeCancelRoute: SubscribeCancelRoute,
  SubscribeSuccessRoute: SubscribeSuccessRoute,
}

const SubscribeRouteWithChildren = SubscribeRoute._addFileChildren(
  SubscribeRouteChildren,
)

interface TemplatesRouteChildren {
  TemplatesMarketplaceListingIdRoute: typeof TemplatesMarketplaceListingIdRoute
  TemplatesMarketplaceIndexRoute: typeof TemplatesMarketplaceIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesMarketplaceListingIdRoute: TemplatesMarketplaceListingIdRoute,
  TemplatesMarketplaceIndexRoute: TemplatesMarketplaceIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiEstimateRoute: AiEstimateRoute,
  AnalyticsRoute: AnalyticsRoute,
  AutomationRoute: AutomationRoute,
  BlogRoute: BlogRoute,
  ChangeOrdersRoute: ChangeOrdersRouteWithChildren,
  ContractsRoute: ContractsRouteWithChildren,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DownloadFreeEstimatingTemplateRoute: DownloadFreeEstimatingTemplateRoute,
  EstimatesRoute: EstimatesRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImportRoute: ImportRoute,
  IntegrationsRoute: IntegrationsRoute,
  InvoicesRoute: InvoicesRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  MaterialsRoute: MaterialsRoute,
  OnboardingRoute: OnboardingRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PipelineRoute: PipelineRoute,
  PortalAccessRoute: PortalAccessRoute,
  PriceListsRoute: PriceListsRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRoute,
  SignupRoute: SignupRoute,
  SubcontractorsRoute: SubcontractorsRoute,
  SubscribeRoute: SubscribeRouteWithChildren,
  TakeoffRoute: TakeoffRoute,
  TeamRoute: TeamRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  CoIdRoute: CoIdRoute,
  PortalLoginRoute: PortalLoginRoute,
  SignEstimateIdRoute: SignEstimateIdRoute,
  TradeSlugRoute: TradeSlugRoute,
  ViewTokenRoute: ViewTokenRoute,
  FreeEstimatingTemplatePdfIndexRoute: FreeEstimatingTemplatePdfIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalChangeOrderIdRoute: PortalChangeOrderIdRoute,
  PortalEstimateIdRoute: PortalEstimateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
